#!/bin/bash

function print_usage() {
   echo "usage:"
   echo "$0 mask"
   echo "$0 unmask"
   echo "mask disables suspend"
   echo "unmask enables suspend"
}

if [ $# != 1 ]; then
   print_usage
   exit
fi

case $1 in
  mask)
    sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
    echo "hibernation and suspend disabled"
    ;;
  unmask)
    sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target
    echo "hibernation and suspend enabled"
    ;;
  *)
    print_usage
    ;;
esac
